services:
  liloc_ros2:
    build:
      context: ..
      dockerfile: docker/dockerfile
    image: liloc_ros2
    container_name: liloc_ros2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Needed to display RViz within the container
      - ../:/root/ros2_ws/src/liloc/
      - ${HOME}/data_sets:/root/ros2_ws/data_sets
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY: "${DISPLAY}"
      ROS_DOMAIN_ID: 36
    network_mode: host
    stdin_open: true
    tty: true
    runtime: nvidia
    command: ["bash"]
    