# Start from a ROS ${ROS_DISTRO} base image.
ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}

# Install common build tools and necessary dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    keyboard-configuration \
    software-properties-common \
    && add-apt-repository ppa:borglab/gtsam-develop \
    && apt-get install -y \
    cmake \
    nano \
    vim \
    libpcl-dev \
    libeigen3-dev \
    libopencv-dev \
    libgtsam-dev \
    # libgtsam-unstable-dev \
    pcl-tools \
    && rm -rf /var/lib/apt/lists/*

# --- Install ROS Dependencies ---
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-${ROS_DISTRO}-rviz2 \
    ros-${ROS_DISTRO}-cv-bridge \
    ros-${ROS_DISTRO}-pcl-conversions \
    ros-${ROS_DISTRO}-rqt-graph \
    && rm -rf /var/lib/apt/lists/*

# --- Install Livox SDK and ROS Driver ---
WORKDIR /root
# Livox SDK
RUN git clone https://github.com/Livox-SDK/Livox-SDK2.git && \
    cd Livox-SDK2 && \
    mkdir build && \
    cd build && cmake .. && \
    make -j && \
    make install
# Livox ROS Driver
RUN git clone https://github.com/Livox-SDK/livox_ros_driver2.git ws_livox/src/livox_ros_driver2 && \
    cd ws_livox/src/livox_ros_driver2 && \
    . /opt/ros/${ROS_DISTRO}/setup.sh && \
    ./build.sh humble

# --- Create a catkin workspace ---
ENV ROS2_WS=/root/ros2_ws
WORKDIR ${ROS2_WS}/src

# Clone dependencies
RUN git clone https://github.com/koide3/ndt_omp.git && \
    cd .. && \
    /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
    colcon build --symlink-install --packages-select ndt_omp"

# Copy in LiLoc source code
COPY . ./liloc/

# Build the ROS workspace
WORKDIR ${ROS2_WS}
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
    source ~/ws_livox/install/setup.bash && \
    source install/setup.bash && \
    colcon build --symlink-install --packages-select liloc"

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc && \
    echo "source ~/ws_livox/install/setup.bash" >> ~/.bashrc && \
    echo "if [ -f ~/ros2_ws/install/setup.bash ]; then" >> ~/.bashrc && \
    echo "  source ~/ros2_ws/install/setup.bash" >> ~/.bashrc && \
    echo "fi" >> ~/.bashrc
